### ISSUE TITLE
Suggestion: Symbolic Icon

### ISSUE THREAD

**Issue by algatern** [G-dH/gnome-colorblind-filters#13]
To make this extension look more native, it would be nice to replace the top bar icon with Gnome Adwaita's native symbolic icon.

![Screenshot from 2023-03-22 13-41-24](https://user-images.githubusercontent.com/119867306/226992065-e033e20a-9fc5-4641-8565-a1f35d10c475.png)

 I tested this myself by replacing the icons in the extension folder with Gnome's Adwaita icons located here:
`/usr/share/icons/Adwaita/scalable/actions/view-reveal-symbolic.svg`
and
`/usr/share/icons/Adwaita/scalable/actions/view-conceal-symbolic.svg`

This looks more official and blends nicely with the existing UI.

**Comment by G-dH** [comment]
Thanks for the suggestion, I didn't notice the 'conceal' version of the icon so made it from the ubuntu symbolic icon.

**Comment by G-dH** [comment]
Fixed, released with version 16.
