### ISSUE TITLE
shaders being merged into gnome?

### ISSUE THREAD

**Issue by 24fpsDaVinci** [G-dH/gnome-colorblind-filters#20]
is this still happening?

**Comment by G-dH** [comment]
I don't understand the question..

**Comment by 24fpsDaVinci** [comment]
sorry i forgot to include the link. There was some talk to merge shaders.js into gnome here:
https://gitlab.gnome.org/GNOME/gnome-control-center/-/issues/2416

**Comment by G-dH** [comment]
It's not my initiative and nothing is happening as far as I can see..

**Comment by 24fpsDaVinci** [comment]
since the proposal has stalled, will we see gnome 45 support for this extension?

**Comment by G-dH** [comment]
It's already available in the `esm-modules` branch of this repository.

**Comment by 24fpsDaVinci** [comment]
it appears [esm-modules branch ](https://github.com/G-dH/gnome-colorblind-filters/tree/esm-modules) was not updated since 6 months ago?

**Comment by G-dH** [comment]
Sorry, my bad, I forgot to push my local updates to the repository. I'll do it today.

**Comment by G-dH** [comment]
Updated
