### ISSUE TITLE
does not work in firefox fullscreen mode

### ISSUE THREAD

**Issue by 24fpsDaVinci** [G-dH/gnome-colorblind-filters#22]
I tested firefox, firefox nightly, firefox flatpak
the colorblind extension does not work in fullscreen mode for firefox and firefox nightly but works in firefox flatpak
i'm using wayland fedora 39

**Comment by G-dH** [comment]
CBF adds an effect to the GNOME Shell stage, but cannot control rendering outside the Shell.

**Comment by 24fpsDaVinci** [comment]
i found a temp workaround using accessibility > zoom at 1x magnification and this extension. downside is you lose a few fps
