### ISSUE TITLE
request: GNOME 3.28 compatibility

### ISSUE THREAD

**Issue by katkauma** [G-dH/gnome-colorblind-filters#23]
Hello,

Would it be possible for you to make this compatible with Gnome 3.28? My work desktop runs that version and I am unable change it (OS: Red Hat Enterprise 7.9, with gnome 3.28.2).  I have used this extension on my more up-to-date laptop and found it incredibly helpful when making plots and figures.  I would love to be able to use it on my work computer as well.

**Comment by G-dH** [comment]
Hello, I'm afraid it won't be trivial. Try to [install the extension from this repository](https://github.com/G-dH/gnome-colorblind-filters#gnome-336---44), edit `~/.local/share/gnome-shell/extensions/colorblind-filters@G-dH.github.com/metadata.json` file, add `"3.28"` to the `shell-version:` list, restart Shell, enable extension and see if it works. If not, open a terminal, execute `journalctl /usr/bin/gnome-shell -e` and check for errors.

**Comment by katkauma** [comment]
Thanks for responding!
I am able to enable/disable the extension from Tweaks, but nothing happens when I do.  
The error associated with this extension is:
`TypeError: GObject.registerClass() used with invalid base class (is PanelMenuButton)`

**Comment by G-dH** [comment]
Sorry, I'd love to help you, but it's too time-consuming for me.
