### ISSUE TITLE
GNOME 46 support

### ISSUE THREAD

**Issue by MikeWent** [G-dH/gnome-colorblind-filters#25]
Simple [version bump](https://github.com/MikeWent/gnome-colorblind-filters/commit/4a87afc456bf7cec5618d919d3e25d5f89a05cd2) to run on 46 produces an error:

```
gnome-shell[7673]: Extension colorblind-filters@G-dH.github.com: SyntaxError: import declarations may only appear at top level of a module @ resource:///org/gnome/shell/ui/main.js:3:0

    Stack trace:
        @file:///home/mike/.local/share/gnome-shell/extensions/colorblind-filters@G-dH.github.com/extension.js:13:14
        @resource:///org/gnome/shell/ui/init.js:21:20
```

Please add GNOME 46 support

**Comment by G-dH** [comment]
You bumped a wrong branch, 45 is supported in `esm-modules` branch.
However, I'll move it to `main` and add the support for 46 soon.

**Comment by G-dH** [comment]
The repository has been updated, the `main` version now supports GNOME 45,46. I'll send it to e.g.o soon.

**Comment by G-dH** [comment]
Released on e.g.o now.
